// Comprehensive Flight Data & Airports for VoyaFlights Platform

const AIRPORTS = [
  { code: 'JFK', city: 'New York', country: 'United States', airport: 'John F. Kennedy Intl (JFK)' },
  { code: 'DPS', city: 'Bali', country: 'Indonesia', airport: 'Ngurah Rai Intl (DPS)' },
  { code: 'MLE', city: 'Maldives', country: 'Maldives', airport: 'Velana Intl (MLE)' },
  { code: 'DXB', city: 'Dubai', country: 'United Arab Emirates', airport: 'Dubai Intl (DXB)' },
  { code: 'LHR', city: 'London', country: 'United Kingdom', airport: 'Heathrow Airport (LHR)' },
  { code: 'SIN', city: 'Singapore', country: 'Singapore', airport: 'Singapore Changi (SIN)' },
  { code: 'CDG', city: 'Paris', country: 'France', airport: 'Charles de Gaulle (CDG)' },
  { code: 'HND', city: 'Tokyo', country: 'Japan', airport: 'Tokyo Haneda (HND)' },
  { code: 'DEL', city: 'New Delhi', country: 'India', airport: 'Indira Gandhi Intl (DEL)' },
  { code: 'BOM', city: 'Mumbai', country: 'India', airport: 'Chhatrapati Shivaji Intl (BOM)' },
  { code: 'CUN', city: 'Cancún', country: 'Mexico', airport: 'Cancun Intl (CUN)' },
  { code: 'JTR', city: 'Santorini', country: 'Greece', airport: 'Santorini Thira (JTR)' },
  { code: 'BOD', city: 'Bora Bora', country: 'French Polynesia', airport: 'Motu Mute (BOB)' },
  { code: 'SYD', city: 'Sydney', country: 'Australia', airport: 'Sydney Kingsford Smith (SYD)' }
];

const FLIGHTS_DATABASE = [
  {
    id: 'FL-EK899',
    airline: 'Emirates',
    airlineCode: 'EK',
    flightNumber: 'EK-204',
    logo: '🇦🇪',
    from: 'JFK',
    fromCity: 'New York',
    to: 'DPS',
    toCity: 'Bali',
    departureTime: '08:30',
    arrivalTime: '19:00',
    arrivalDayOffset: '+1',
    duration: '22h 30m',
    durationMinutes: 1350,
    stops: '1 Stop (DXB)',
    stopsCount: 1,
    price: 899,
    originalPrice: 1120,
    discount: '20% OFF',
    tripType: 'Round trip',
    category: 'best-price',
    baggage: '25kg Baggage Included',
    aircraft: 'Boeing 777-300ER',
    seatsLeft: 5,
    meal: 'Complimentary Halal/International Meal',
    rating: 4.9,
    isPopular: true
  },
  {
    id: 'FL-QR928',
    airline: 'Qatar Airways',
    airlineCode: 'QR',
    flightNumber: 'QR-702',
    logo: '🇶🇦',
    from: 'JFK',
    fromCity: 'New York',
    to: 'DPS',
    toCity: 'Bali',
    departureTime: '09:15',
    arrivalTime: '21:25',
    arrivalDayOffset: '+1',
    duration: '23h 10m',
    durationMinutes: 1390,
    stops: '1 Stop (DOH)',
    stopsCount: 1,
    price: 928,
    originalPrice: 1150,
    discount: '15% OFF',
    tripType: 'Round trip',
    category: 'popular',
    baggage: '30kg Baggage Included',
    aircraft: 'Airbus A350-1000',
    seatsLeft: 3,
    meal: 'Multi-course In-Flight Dining',
    rating: 4.95,
    isPopular: false
  },
  {
    id: 'FL-SQ956',
    airline: 'Singapore Airlines',
    airlineCode: 'SQ',
    flightNumber: 'SQ-25',
    logo: '🇸🇬',
    from: 'JFK',
    fromCity: 'New York',
    to: 'DPS',
    toCity: 'Bali',
    departureTime: '10:45',
    arrivalTime: '21:30',
    arrivalDayOffset: '+1',
    duration: '21h 45m',
    durationMinutes: 1305,
    stops: '1 Stop (SIN)',
    stopsCount: 1,
    price: 956,
    originalPrice: 1250,
    discount: '18% OFF',
    tripType: 'Round trip',
    category: 'fastest',
    baggage: '30kg Baggage Included',
    aircraft: 'Airbus A380 Superjumbo',
    seatsLeft: 4,
    meal: 'Signature Chef Selection',
    rating: 4.98,
    isPopular: false
  },
  {
    id: 'FL-EY878',
    airline: 'Etihad Airways',
    airlineCode: 'EY',
    flightNumber: 'EY-100',
    logo: '🇦🇪',
    from: 'JFK',
    fromCity: 'New York',
    to: 'DPS',
    toCity: 'Bali',
    departureTime: '11:30',
    arrivalTime: '22:50',
    arrivalDayOffset: '+1',
    duration: '22h 20m',
    durationMinutes: 1340,
    stops: '1 Stop (AUH)',
    stopsCount: 1,
    price: 878,
    originalPrice: 1080,
    discount: '22% OFF',
    tripType: 'Round trip',
    category: 'best-price',
    baggage: '23kg Baggage Included',
    aircraft: 'Boeing 787-9 Dreamliner',
    seatsLeft: 7,
    meal: 'Complimentary Warm Meals & Drinks',
    rating: 4.8,
    isPopular: false
  },
  {
    id: 'FL-DL645',
    airline: 'Delta Air Lines',
    airlineCode: 'DL',
    flightNumber: 'DL-162',
    logo: '🇺🇸',
    from: 'JFK',
    fromCity: 'New York',
    to: 'DPS',
    toCity: 'Bali',
    departureTime: '06:30',
    arrivalTime: '17:15',
    arrivalDayOffset: '+1',
    duration: '21h 45m',
    durationMinutes: 1305,
    stops: '1 Stop (ICN)',
    stopsCount: 1,
    price: 945,
    originalPrice: 1190,
    discount: '12% OFF',
    tripType: 'Round trip',
    category: 'earliest',
    baggage: '2 x 23kg Bags',
    aircraft: 'Airbus A350-900',
    seatsLeft: 6,
    meal: 'Free Wi-Fi & Starbuck Coffee',
    rating: 4.75,
    isPopular: false
  },
  {
    id: 'FL-BA710',
    airline: 'British Airways',
    airlineCode: 'BA',
    flightNumber: 'BA-178',
    logo: '🇬🇧',
    from: 'JFK',
    fromCity: 'New York',
    to: 'DPS',
    toCity: 'Bali',
    departureTime: '07:15',
    arrivalTime: '19:45',
    arrivalDayOffset: '+1',
    duration: '23h 30m',
    durationMinutes: 1410,
    stops: '1 Stop (LHR)',
    stopsCount: 1,
    price: 910,
    originalPrice: 1130,
    discount: '15% OFF',
    tripType: 'Round trip',
    category: 'earliest',
    baggage: '23kg Baggage Included',
    aircraft: 'Boeing 777',
    seatsLeft: 8,
    meal: 'Full English / Continental Dining',
    rating: 4.7,
    isPopular: false
  }
];

// Popular Flight Destinations
const POPULAR_DESTINATIONS = [
  {
    id: 'dest-mle',
    city: 'Maldives',
    code: 'MLE',
    region: 'Indian Ocean',
    country: 'Maldives',
    price: 899,
    originalPrice: 1150,
    discount: '20% OFF',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=80',
    features: ['Direct Flights Available', 'Free 25kg Baggage Included', 'Complimentary In-Flight Meals'],
    tags: ['Tropical', 'Luxury', 'Beach']
  },
  {
    id: 'dest-bob',
    city: 'Bora Bora',
    code: 'BOB',
    region: 'French Polynesia',
    country: 'French Polynesia',
    price: 1099,
    originalPrice: 1399,
    discount: '15% OFF',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    features: ['Scenic Island Transfer', 'Flexible Booking', 'Free Seat Selection'],
    tags: ['Paradise', 'Honeymoon']
  },
  {
    id: 'dest-jtr',
    city: 'Santorini',
    code: 'JTR',
    region: 'Aegean Sea',
    country: 'Greece',
    price: 799,
    originalPrice: 999,
    discount: '25% OFF',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=800&q=80',
    features: ['Direct Euro Flight', '24/7 Airline Support', 'Priority Boarding'],
    tags: ['Culture', 'Romantic']
  },
  {
    id: 'dest-dps',
    city: 'Bali',
    code: 'DPS',
    region: 'Southeast Asia',
    country: 'Indonesia',
    price: 649,
    originalPrice: 850,
    discount: '25% OFF',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80',
    features: ['Top Rated Airlines', 'Eco Friendly Flights', 'Snack & Drinks Included'],
    tags: ['Adventure', 'Nature']
  },
  {
    id: 'dest-dxb',
    city: 'Dubai',
    code: 'DXB',
    region: 'Middle East',
    country: 'UAE',
    price: 999,
    originalPrice: 1299,
    discount: '30% OFF',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=80',
    features: ['A380 Luxury Experience', 'Chauffeur Service eligible', 'Extra Legroom'],
    tags: ['Luxury', 'Shopping']
  },
  {
    id: 'dest-cun',
    city: 'Cancún',
    code: 'CUN',
    region: 'Caribbean',
    country: 'Mexico',
    price: 699,
    originalPrice: 899,
    discount: '20% OFF',
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    features: ['Non-Stop Daily Flights', 'Free Carry-on', 'Instant E-Ticket'],
    tags: ['Resort', 'Beaches']
  }
];

// Special Flight Deals & Offers
const TOP_FLIGHT_DEALS = [
  {
    id: 'deal-1',
    title: 'Maldives Paradise Flight',
    route: 'New York (JFK) ➔ Maldives (MLE)',
    discount: '30% OFF',
    price: 699,
    originalPrice: 999,
    type: 'Roundtrip • Non-stop • Meals & 25kg Bag',
    image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=600&q=80',
    airline: 'Emirates',
    validUntil: 'Limited seats available'
  },
  {
    id: 'deal-2',
    title: 'Iceland Arctic Express',
    route: 'London (LHR) ➔ Reykjavik (KEF)',
    discount: '15% OFF',
    price: 779,
    originalPrice: 920,
    type: 'Roundtrip • Direct • Free Cabin Baggage',
    image: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?auto=format&fit=crop&w=600&q=80',
    airline: 'Icelandair',
    validUntil: 'Book before Friday'
  },
  {
    id: 'deal-3',
    title: 'Bali Island Adventure Air',
    route: 'Sydney (SYD) ➔ Bali (DPS)',
    discount: '25% OFF',
    price: 699,
    originalPrice: 929,
    type: 'Roundtrip • Non-stop • 30kg Allowance',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=600&q=80',
    airline: 'Garuda Indonesia',
    validUntil: 'Super Saver Fare'
  },
  {
    id: 'deal-4',
    title: 'Dubai Skylight Flight',
    route: 'Paris (CDG) ➔ Dubai (DXB)',
    discount: '30% OFF',
    price: 899,
    originalPrice: 1299,
    type: 'Roundtrip • Direct A380 • Premium Meals',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=600&q=80',
    airline: 'Emirates',
    validUntil: 'Flash Sale'
  }
];

// Cabin Experience Plans
const CABIN_PLANS = [
  {
    id: 'plan-economy',
    title: 'Solo Explorer',
    subtitle: 'Perfect for solo flyers seeking adventure & value.',
    price: 499,
    badge: 'Popular',
    icon: '🎒',
    features: [
      'Standard Ergonomic Recliner Seat',
      'Free 7kg Carry-on + 23kg Check-in',
      'Standard In-Flight Entertainment',
      'Complimentary Beverage Service'
    ]
  },
  {
    id: 'plan-premium',
    title: 'Couple Gateway',
    subtitle: 'Extra comfort and romantic perks made memorable.',
    price: 799,
    badge: 'Most Popular',
    featured: true,
    icon: '✈️',
    features: [
      'Side-by-Side Seats Guaranteed',
      '38-inch Extra Legroom & Footrest',
      'Premium Dining & Wine Selection',
      'Priority Check-in & Fast Track',
      '2 x 25kg Checked Baggage'
    ]
  },
  {
    id: 'plan-first',
    title: 'Family & First Class',
    subtitle: 'Luxurious private suites and seamless family flying.',
    price: 1299,
    badge: 'Luxury Class',
    icon: '👑',
    features: [
      'Fully Flat Lie-down Bed Suites',
      'Lounge Access at All Airports',
      'Chauffeur Airport Pickup',
      'Gourmet À la Carte Dining Anytime',
      'Unlimited High-Speed Sky Wi-Fi'
    ]
  }
];

// Flyer Testimonials
const TESTIMONIALS = [
  {
    name: 'Emily R.',
    location: 'New York, USA',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
    rating: 5,
    quote: 'The flight booking was beyond smooth! Finding direct JFK to DPS tickets at $899 saved us over $400. Real-time gate alerts were invaluable.',
    route: 'JFK ➔ Bali (Emirates)'
  },
  {
    name: 'James T.',
    location: 'London, UK',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    rating: 5,
    quote: 'Best flight reservation system ever! Every detail, from seat selection to baggage rules, was transparent with zero hidden fees.',
    route: 'LHR ➔ Dubai (Etihad)'
  },
  {
    name: 'Sophia L.',
    location: 'Sydney, Australia',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    rating: 5,
    quote: 'Highly recommended! We rescheduled our return flight to the Maldives with zero hassle using their 24/7 flight concierge.',
    route: 'SYD ➔ Maldives (Singapore Airlines)'
  }
];
